# Generated by Django 4.0.4 on 2023-05-02 12:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hwinterface',
            name='current_device_path',
            field=models.JSONField(default=dict, max_length=1024, validators=[core.validators.validate_hw_interface_current_device_path]),
        ),
    ]
