# Generated by Django 4.0.4 on 2023-06-07 06:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_license_disabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='backendevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AddField(
            model_name='backendevent',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.usergroup'),
        ),
        migrations.AddField(
            model_name='license',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.usergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.usergroup'),
        ),
    ]
