# Generated by Django 4.0.4 on 2023-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usergroup_remove_backendevent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendevent',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='backend_events', to='core.usergroup'),
        ),
        migrations.AlterField(
            model_name='license',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='core.usergroup'),
        ),
    ]
